meta_product_name: "Kevin"
meta_title: "Kevin - Your relationship assistant"
meta_description: "Have you ever asked yourself.. what's his name again? Forgot where you've meet someone you know? Don't quite remember or mixup which friends likes what. Fear no more! Just rememeber to use Kevin from now on"
meta_image: "kevin_meta.png" # should exist in `app/assets/images/`
