meta_product_name: "Kevin"
meta_title: "Kevin - Your relationship assistant"
meta_description: "Have you ever asked yourself.. what's their name again? Where you know them from? Do they love peanuts or are they alergic to them? You might not want to take a guess on that one. Fear no more! Kevin, your relatioship assistant as got your back."
meta_image: "kevin_meta.png" # should exist in `app/assets/images/`
